---
title: "hyp_growth_ODE"
output: html_notebook
---

```{r}
library(tidyverse)
library(dMod)
```


## Set up model

reactions
```{r}
r <- eqnlist() %>%
  addReaction(from="",
              to="PIFmRNA",
              rate="(1+cos((time+phase)/24*2*3.141593))*amplitude",
              description="PIF mRNA synthesis") %>%
  addReaction(from="PIFmRNA",
              to="",
              rate="k1*PIFmRNA",
              description = "PIF mRNA degradation") %>%
  addReaction(from="",
              to="PIFprotein",
              rate="k2*PIFmRNA",
              description = "PIF protein synthesis") %>%
  addReaction(from="PIFprotein",
              to="",
              rate = "(k3*light+k4)*PIFprotein",
              description = "PIF protein degradation") %>%
  addReaction(from="",
              to="growth",
              rate="k5*PIFprotein",
              description = "PIF growth control") %>%
  addReaction(from="growth",
              to="",
              rate="k6*growth",
              description="cessation of growth")

r
```

generate model

```{r}
model0 <- odemodel(r, modelname="rna", compile = TRUE, forcings = "light")
```


specify time and light on/off events

```{r}
times <- seq(0, 120, len=2000)

light.forcing <- data.frame(
  name="light",
  time=times,
  value=as.numeric((times %% 24 ) < 8))

light.forcing
```

generate prediction function
```{r}
x <- Xs(model0, forcings = light.forcing)
```


add parameters

```{r}
parameters <- getParameters(x)

parameters

pars <- c(
  "PIFmRNA" = 0,
  "PIFprotein" = 0,
  "growth" = 0,
  "phase" = 0,
  "amplitude" = 1,
  "k1" = 1,
  "k2" = 1,
  "k3" = 5,
  "k4" = .1,
  "k5" = 1,
  "k6" = 1
)

pars

```

predict
```{r}
prediction <- x(times, pars)

plot(prediction)
```


## parameter estimation

now try to estimate parameters based on observed data.  Start with Col only:



```{r}
col <- read.csv("data/Col.csv") %>%
  mutate(name="growth", condition="col") %>%
  mutate(sigma=0.05*value) %>%
  select(name, time, value, sigma, condition)

col <- as.datalist(col,split.by="condition")
```

```{r}
plot(col)
```


convert parameters to eqn form:

```{r}
p <- eqnvec() %>%
  define("x~x", x = getParameters(x)) %>%
  define("x ~ 0", x=c("PIFmRNA", "PIFprotein", "growth")) %>%
  insert("x ~ exp(x)", x = c("k1", "k2", "k3", "k4", "k5", "k6")) %>% # keep rates positive
  P(condition = "col")

getEquations(p)
```

objective function
```{r}
obj <- normL2(col, x*p)
```

Fit the data

```{r}
mu <- structure(rep(0, length(parameters)), names = parameters)
constr <- constraintL2(mu = mu, sigma = 5)
myfit <- trust(obj + constr, mu, rinit = 1, rmax = 1000, iterlim = 1000)
myfit$argument
```

plot it
```{r}
times <- 0:80
plot((x*p)(times, myfit$argument), col)
```

```{r}
fitlist <- mstrust(obj + constr,
                   center =myfit$argument,
                   fits=60,
                   cores = 3,
                   iterlim = 1000,
                   sd=2)
```

```{r}
pars <- as.parframe(fitlist)
plotValues(pars, tol = 10)
```

plot the best one
```{r}
plot((x*p)(times, pars[1,]), col)
```

better plot 
```{r}
prediction <- predict(x*p, times = times, pars = pars[1,], data=col)
prediction %>%
  filter(name=="growth") %>%
  ggplot(aes(x=time, y = value)) +
  geom_line() +
  geom_point(data = attr(prediction, "data"), color="red") +
  geom_vline(xintercept =c(0, 8, 24, 32, 48, 56, 72, 80))
```

